name: day-43-task4

on:
    workflow_dispatch:
jobs:
    task4:
        runs-on: ubuntu-latest
        steps:
            - name: Run only on main
              if: github.ref == 'refs/heads/main'
              run: echo "This is the main branch"

            - name: Error step
              id: step_error
              continue-on-error: true
              run: |
                echo "Simulating Failure"
                exit 1

            - name: Check Previous step
              if: steps.step_error.outcome == 'failure'
              run: echo "Previous Step failed but I am running"
              
        
              
              
